name: BT-Core Build Component in Native Environment

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  native-build:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------------
      # Checkout
      # ----------------------------------------
      - name: Checkout source
        uses: actions/checkout@v6

      # ----------------------------------------
      # Setup scripts permission
      # ----------------------------------------
      - name: Make scripts executable
        run: |
          chmod +x build_dependencies.sh
          chmod +x cov_build.sh

      # ----------------------------------------
      # Install dependencies
      # ----------------------------------------
      - name: Run bt-core dependency setup
        run: ./build_dependencies.sh

      # ----------------------------------------
      # Build project
      # ----------------------------------------
      - name: Run bt-core native build
        run: ./cov_build.sh
